"""Support ticket changes

Revision ID: 77f8c4a5ec7b
Revises: 9a997ea48487
Create Date: 2023-12-02 21:51:40.503651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f8c4a5ec7b'
down_revision: Union[str, None] = '9a997ea48487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
