"""Support ticket close requests counter

Revision ID: 665b686e24af
Revises: fb152428a709
Create Date: 2023-11-29 22:31:40.032312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665b686e24af'
down_revision: Union[str, None] = 'fb152428a709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('close_requests', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'close_requests')
    # ### end Alembic commands ###
