"""TicketMessages changes

Revision ID: d274c924f3d5
Revises: a74ffabc16c0
Create Date: 2023-11-30 19:54:12.008131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd274c924f3d5'
down_revision: Union[str, None] = 'a74ffabc16c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('close_requests_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'close_requests_ids')
    # ### end Alembic commands ###
