"""TicketMessages changes

Revision ID: a74ffabc16c0
Revises: ca114cd7d1c4
Create Date: 2023-11-30 15:54:35.879634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74ffabc16c0'
down_revision: Union[str, None] = 'ca114cd7d1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_messages', sa.Column('message_text', sa.Text(), nullable=True))
    op.add_column('ticket_messages', sa.Column('sender_username', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_messages', 'sender_username')
    op.drop_column('ticket_messages', 'message_text')
    # ### end Alembic commands ###
