"""TicketMessages changes

Revision ID: 33a1fc5307cf
Revises: 7df3dbb9cfe1
Create Date: 2023-12-02 02:59:42.606846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a1fc5307cf'
down_revision: Union[str, None] = '7df3dbb9cfe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('panel', sa.String(length=100), nullable=True))
    op.add_column('support_tickets', sa.Column('link', sa.String(), nullable=True))
    op.add_column('support_tickets', sa.Column('login', sa.String(), nullable=True))
    op.add_column('support_tickets', sa.Column('password', sa.String(), nullable=True))
    op.add_column('support_tickets', sa.Column('steam_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'steam_id')
    op.drop_column('support_tickets', 'password')
    op.drop_column('support_tickets', 'login')
    op.drop_column('support_tickets', 'link')
    op.drop_column('support_tickets', 'panel')
    # ### end Alembic commands ###
