"""TicketMessages and m2m relationshiop between tickets and their messages

Revision ID: b5c8445bb566
Revises: 5f2f86e2697d
Create Date: 2023-11-30 15:04:22.897515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b5c8445bb566'
down_revision: Union[str, None] = '5f2f86e2697d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_messages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('messages_id', sa.BIGINT(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('support_tickets_messages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('support_ticket_id', sa.Integer(), nullable=False),
                    sa.Column('ticket_message_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['support_ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['ticket_message_id'], ['ticket_messages.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_tickets_messages')
    op.drop_table('ticket_messages')
    # ### end Alembic commands ###
