"""Support ticket model

Revision ID: fb152428a709
Revises: 
Create Date: 2023-11-29 21:52:44.073655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fb152428a709'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.BIGINT(), nullable=False),
                    sa.Column('admin_id', sa.BIGINT(), nullable=True),
                    sa.Column('token', sa.String(), nullable=False),
                    sa.Column('closed', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
