"""Messages_id changed to message_id

Revision ID: ca114cd7d1c4
Revises: b5c8445bb566
Create Date: 2023-11-30 15:21:14.649731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca114cd7d1c4'
down_revision: Union[str, None] = 'b5c8445bb566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_messages', sa.Column('message_id', sa.BIGINT(), nullable=False))
    op.drop_column('ticket_messages', 'messages_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_messages', sa.Column('messages_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('ticket_messages', 'message_id')
    # ### end Alembic commands ###
