"""TicketMessages changes

Revision ID: 7df3dbb9cfe1
Revises: d274c924f3d5
Create Date: 2023-12-01 01:13:03.347369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df3dbb9cfe1'
down_revision: Union[str, None] = 'd274c924f3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('user_username', sa.String(length=100), nullable=True))
    op.add_column('support_tickets', sa.Column('admin_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'admin_username')
    op.drop_column('support_tickets', 'user_username')
    # ### end Alembic commands ###
